### ISSUE TITLE
Format chat messages

### ISSUE THREAD

**Issue by rebeccacxy** [bettersg/SchemesSG_v3#15]
<img width="1302" alt="Screenshot 2024-08-15 at 5 27 29 AM" src="https://github.com/user-attachments/assets/2fce0f59-bcfb-4058-b0a0-b19993996533">

**Comment by CJBuzz** [comment]
Hi I've modified schemespal.html on the chatbot branch to format the output properly

**Comment by rebeccacxy** [comment]
@CJBuzz make a PR please
