### ISSUE TITLE
Firebase Function - Submit add/edit scheme form

### ISSUE THREAD

**Issue by yevkim** [bettersg/SchemesSG_v3#53]
Create a branch from stg
Follow the search API structure on accessing firestore database

POST
Take add/edit form data for scheme and store it in schemeEntries

**Comment by sparkli94** [comment]
Thanks, I've had a look at the schemeEntries collection in firebase dev. There are 4 documents in this collection and each document has different fields. 

1. **1weP1thuyFAGjG8T8zGh:** Description, Link, Scraped_Text, scraped_text
2. **9yueLI6tnbt5KSnXCrmN:** Description, Link, Scraped_Text, scraped_text
3. **FiBi2J5KOIvVADPhfu0G:** Changes, Description, Link, Scheme, Scraped_Text, Status, entryId, scraped_text, timestamp
4. **zBVIJUMcyE8WuTENHVqM:** feedbackText, requestUUID, timestamp

**Comment by sparkli94** [comment]
From the Architecture Notion page I can see the specifications of schemeEntries are below:

- Changes
- Description
- Link
- Scheme
- Status
- entryId - was this meant to reflect some existing scheme's unique ID?
- timestamp
- userName
- userEmail

Are any of these fields mandatory? Should I add some null checks?

**Comment by yevkim** [comment]
@sparkli94 Thanks
entryId is just unique UUID or can replace with auto generated document id
let's also add one more field indicator typeOfRequest to indicate new or edit of the scheme 

can keep all fields optional. 
for current schemeEntries, we will discard it. Den was exploring the scraping using that table.

**Comment by sparkli94** [comment]
Thanks @yevkim! I've now created a new MR https://github.com/bettersg/SchemesSG_v3/pull/95 to add in the typeOfRequest field.
